[[language]]
name = "markdown"
text-width = 120
soft-wrap.enable = true
soft-wrap.wrap-at-text-width = true
language-servers = ["marksman"]
formatter = { command = 'prettier', args = [
  "--parser",
  "markdown",
  "--prose-wrap",
  "never",
]}

