#+title: My Emacs Configuration
#+property: header-args :mkdirp yes
#+property: header-args :noweb yes :results silent
#+property: header-args :emacs-lisp :tangle ~/.emacs.d/init.el

* Emacs Configuration

This is my personal Emacs configuration, mostly based upon the [[https://github.com/daviwil/emacs-from-scratch][emacs-from-scratch]] video series made by [[https://github.com/daviwil][David Wilson]]. Of course, his is not the only configuration that I checked out, there are so many great configurations to discover on the net. I try to give credit where credit is due, but I might have forgotten some.

** Basic setup

#+begin_src emacs-lisp
      ;;; init.el -*- lexical-binding: t; -*-
      ;; Tangled from Emacs.org

      ;; Profile emacs startup
      (add-hook 'emacs-startup-hook
    	    (lambda ()
    	      (message "Emacs loaded in %s."
    		       (emacs-init-time))))

      ;; Package management
      (defvar native-comp-deferred-compilation-deny-list ())
      (defvar bootstrap-version)
      (let ((bootstrap-file
    	 (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
    	(bootstrap-version 5))
        (unless (file-exists-p bootstrap-file)
          (with-current-buffer
    	  (url-retrieve-synchronously
    	   "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
    	   'silent 'inhibit-cookies)
    	(goto-char (point-max))
    	(eval-print-last-sexp)))
        (load bootstrap-file nil 'nomessage))

      ;; Use straight.el for use-package expressions
      (straight-use-package 'use-package)

      ;; Always use straight to install on systems other than Linux
      (setq straight-use-package-by-default (not (eq system-type 'gnu/linux)))
      ;; Load the helper package for commands like `straight-x-clean-unused-repos'
      (require 'straight-x)


      ;; Keep our system straight-x-clean-unused-repos;; NOTE: If you want to move everything out of the ~/.emacs.d folder
      ;; reliably, set `user-emacs-directory` before loading no-littering!
      (setq user-emacs-directory (expand-file-name "~/.cache/emacs/")
    	url-history-file     (expand-file-name "url/history" user-emacs-directory))

      ;; Some decluttering
      ;; disables the Emacs functionality that creates backup files. unnecessary if you use a daemon and don't kill buffers.
      (setq make-backup-files nil)
      (setq auto-save-default nil)

      (use-package no-littering
        :straight t)

      ;; no-littering doesn't set this by default so we must place
      ;; auto save files in the same path as it uses for sessions
      (setq auto-save-file-name-transforms
    	`((".*" ,(no-littering-expand-var-file-name "auto-save/") t)))

      ;; Emacs saves all customizations in init.el by default. I prefer
      ;; to keep the customizations in a seperate file
      (setq custom-file (no-littering-expand-etc-file-name "custom.el"))
      (setq auto-save-list-file-prefix "~/.emacs.d/autosave/")

      ;; Set up the visible bell
      (setq visible-bell t)

      ;; Set default coding system (especially for Windows)
      (set-default-coding-systems 'utf-8)
      (customize-set-variable 'visible-bell 1)  ; turn off beeps, make them flash!
      (customize-set-variable 'large-file-warning-threshold 100000000) ;; change to ~100 MB

#+end_src

*** Themes

I really like the [[https://github.com/hlissner/emacs-doom-themes][Doom themes collection]], especially =vibrant= and =palenight=. For now, lets go with the former. Note that the function =doom-themes-visual-bell-config= enables flashing the mode-line on error.

#+begin_src emacs-lisp

  (use-package doom-themes
    :straight t
    :init
    ;; (load-theme 'doom-palenight t)
    (load-theme 'doom-palenight t)
    (doom-themes-visual-bell-config))

#+end_src

*** Font

Different platforms need different default font sizes; [[https://mozilla.github.io/Fira/][Fira Mono]] was my favorite face, but I'm trying out =Jetbrains Mono= atm.

#+begin_src emacs-lisp

  ;; Set the font face based on platform
  (set-face-attribute 'default nil
                      ;; :font "JetBrains Mono"
                      :font "Inconsolata Nerd Font Mono"
                      :weight 'light
                      :height 125)

  ;; Set the fixed pitch face
  (set-face-attribute 'fixed-pitch nil
                      ;; :font "JetBrains Mono"
                      :font "Inconsolata Nerd Font Mono"
                      :weight 'light
                      :height 115)

  ;; Set the variable pitch face
  (set-face-attribute 'variable-pitch nil
                      ;;:font "Cantarell"
                      ;;:font "Iosevka Nerd Font Mono"
                      :font "FiraCode Nerd Font"
                      :height 115
                      :weight 'regular)

#+end_src

*** Modeline

For modeline customization there is =Doom Modeline= which allows for extensive [[https://github.com/seagle0128/doom-modeline#customize][customization]]. Below is a pretty basic configuration. It does however require the installation of all-the-icons font: =M-x all-the-icons-install-fonts=.

#+begin_src emacs-lisp

  (use-package all-the-icons
    :straight t)

  (use-package doom-modeline
    :straight t
    :after eshell
    :init
    (doom-modeline-mode 1)
    :custom
    (doom-modeline-height 20)
    (doom-modeline-bar-width 6)
    (doom-modeline-major-mode-icon nil))

#+end_src

*** Auto-Reverting Changed Files

#+begin_src emacs-lisp
  
  ;; Revert Dired and other buffers
  (setq global-auto-revert-non-file-buffers t)
  
  ;; Revert buffers when the underlying file has changed
  (global-auto-revert-mode 1)
  
#+end_src

** Update Load Path

This is the folder which among others contains the desktop library.

#+begin_src emacs-lisp :tangle no

  (push "~/.emacs.d/lisp" load-path)

#+end_src

** UI
*** Basic

Set some personal information

#+begin_src emacs-lisp
  
  (setq user-full-name "Mark Broeders"
        user-mail-address "mail@markbroeders.nl")
  
#+end_src

Improve scrolling.

#+begin_src emacs-lisp
  
  (setq mouse-wheel-scroll-amount '(1 ((shift) . 1))) ;; one line at a time
  (setq mouse-wheel-progressive-speed nil) ;; don't accelerate scrolling
  (setq mouse-wheel-follow-mouse 't) ;; scroll window under mouse
  (setq scroll-step 1) ;; keyboard scroll one line at a time
  
#+end_src

Set frame transparency and maximize windows by default.

#+begin_src emacs-lisp :tangle no
  
  ;; Disable transparency 
  (set-frame-parameter (selected-frame) 'alpha '(92 . 92))
  (add-to-list 'default-frame-alist '(alpha . (90 . 90)))
  (set-frame-parameter (selected-frame) 'fullscreen 'maximized)
  (add-to-list 'default-frame-alist '(fullscreen . maximized))
  
#+end_src

Enable line numbers and customize their format.

#+begin_src emacs-lisp
  
  (global-display-line-numbers-mode t)
  (column-number-mode)
  
  ;; Disable line numbers for some modes
  (dolist (mode '(org-mode-hook
                  org-agenda-mode-hook
                  term-mode-hook
                  erc-mode-hook
                  shell-mode-hook
                  treemacs-mode-hook
                  vterm-mode-hook
                  eshell-mode-hook))
    (add-hook mode (lambda () (display-line-numbers-mode 0))))
  
#+end_src

Don't warn for following symlinked files

#+begin_src emacs-lisp
  
  (setq vc-follow-symlinks t)
  
#+end_src

Be more granular with undo

#+begin_src emacs-lisp
  
  (setq evil-want-fine-undo t)
  
#+end_src

Replace "yes" or "No" questions with "y" or "n"

#+begin_src emacs-lisp

  (setq use-short-answers t)

#+end_src

*** More icons

#+begin_src emacs-lisp
  (use-package nerd-icons
    :straight t
    :ensure t)

  (use-package nerd-icons-completion
    :straight t
    :ensure t
    :after marginalia
    :config
    (add-hook 'marginalia-mode-hook #'nerd-icons-completion-marginalia-setup))

  (use-package nerd-icons-corfu
    :straight t
    :ensure t
    :after corfu
    :config
    (add-to-list 'corfu-margin-formatters #'nerd-icons-corfu-formatter))

  (use-package nerd-icons-dired
    :straight t
    :ensure t
    :hook
    (dired-mode . nerd-icons-dired-mode))
#+end_src

** Evil Centered Keyboard Configuration

Although not as experienced as most people, I started out with vim. Although my switch to =Emacs= wasn't that bad (I never experienced an /Emacs pinky/), I still mostly prefer the [[https://vim.rtorr.com/][Vim keybindings]]. So, [[https://github.com/emacs-evil/evil][Evil]] to the rescue!

First, make =escape= quit prompts

#+begin_src emacs-lisp
  
  (global-set-key (kbd "<escape>") 'keyboard-escape-quit)

#+end_src

Since I let =evil-mode= take over =C-u= for buffer scrolling, I need to re-bind the =universal-argument= command to another key sequence.  I'm choosing =C-M-u= for this purpose.

#+begin_src emacs-lisp
  
  (global-set-key (kbd "C-M-u") 'universal-argument)

#+end_src

*** General

[[https://github.com/noctuid/general.el][General.el]] is a fantastic package that makes it very easy to create keybindings. One of the things I enjoyed from [[https://github.com/hlissner/doom-emacs][Doom Emacs]] was the =spacebar= as =leader-key=. In this little configuration snippet, I create a function which defines my leader key. This function makes it easy to create keybindings in my config. Note that my main leader-key is =SPC=, however, for easy configuration of extra keybindings I define a second one =C-c=.

#+begin_src emacs-lisp

  (use-package general
    :straight t
    :after evil
    :config

    (general-create-definer mb/leader-key-def
      :keymaps '(normal insert visual emacs)
      :prefix "SPC"
      :global-prefix "C-SPC")

    (general-create-definer mb/local-leader-keys
      :prefix "C-c"))

#+end_src

*** Evil

Evil emulates the keybindings in Emacs and allows for extensive [[https://evil.readthedocs.io/en/latest/index.html][customization]]. Below is a pretty standard and simple configuration. Since =Evil= does not cover all the parts of Emacs, we use an extra package called [[https://github.com/emacs-evil/evil-collection][evil-collection]] which is a collection of additional keybindings for these parts that are not covered by Evil.

#+begin_src emacs-lisp

    (use-package undo-tree
      :straight t
      :init
      (global-undo-tree-mode 1)
      (setq undo-tree-save-history nil))

    ;; Prevent undo tree files from polluting your git repo
    ;; (setq undo-tree-history-directory-alist '(("." . "~/.emacs.d/undo")))

    (use-package evil
      :straight t
      :init
      (setq evil-want-integration t)
      (setq evil-want-keybinding nil)
      (setq evil-want-C-u-scroll t)
      (setq evil-want-C-i-jump nil)
      :config
      (evil-mode 1)
      (define-key evil-insert-state-map (kbd "C-g") 'evil-normal-state)
      (define-key evil-insert-state-map (kbd "C-h") 'evil-delete-backward-char-and-join)

      ;; Use visual line motions even outside of visual-line-mode buffers
      (evil-global-set-key 'motion "j" 'evil-next-visual-line)
      (evil-global-set-key 'motion "k" 'evil-previous-visual-line)
      ;; Same for up/down keys
      (define-key evil-normal-state-map (kbd "<down>") 'evil-next-visual-line)
      (define-key evil-normal-state-map (kbd "<up>") 'evil-previous-visual-line)

      (evil-set-initial-state 'messages-buffer-mode 'normal)
      (evil-set-initial-state 'dashboard-mode 'normal))

    (use-package evil-collection
      :straight t
      :after evil
      :init
      (setq evil-collection-company-use-tng nil)  ;; Is this a bug in evil-collection?
      :config
      (evil-collection-init))

#+end_src

*** Custom Keybindings

#+begin_src emacs-lisp

  (mb/leader-key-def
    ;; APPLICATIONS
    ;; "a"  '(:ignore t   :which-key "Applications")

    "c"   '(:ignore t   :which-key "Configuration")
    "c e" '((lambda () (interactive)
               (find-file "~/.dotfiles/Emacs.org"))       :which-key "Emacs.org")

    "f"   '(:ignore t           :which-key "Files")
    "f f" '(find-file           :which-key "Open file")
    "f r" '(consult-recent-file :which-key "Recent file")

    "j"   '(:ignore t           :which-key "Journal")
    "j j" '(org-journal-new-entry :which-key "Today's journal entry")
    "j s" '(org-journal-search-forever :which-key "Search entries")
    )
    

    ;
                                          ; GTD / ORG FILES
    ;; "o"    '(:ignore t :which-key "Open file")
    ;; "o b"  '((lambda () (interactive)
    ;;            (find-file "~/Documents/org/gtd/books.org"))    :which-key "Books.org")
    ;; "o i"  '((lambda () (interactive)
    ;;            (find-file "~/Documents/org/gtd/inbox.org"))    :which-key "Inbox.org")
    ;; "o n"  '((lambda () (interactive)
    ;;            (find-file "~/Documents/org/gtd/main.org"))     :which-key "Notes.org")
    ;; "o p"  '((lambda () (interactive)
    ;;            (find-file "~/Documents/org/gtd/projects.org")) :which-key "Projects.org")

#+end_src

*** Which-key

[[https://github.com/justbur/emacs-which-key][Which-key]] is great for getting an overview of what keybindings are available
based on the prefix keys you entered. I set the delay quite low to 0.3 seconds. Increase this time to wait longer for the popup window.

#+begin_src emacs-lisp
  
  (use-package which-key
    :straight t
    :init (which-key-mode)
    :diminish which-key-mode
    :config
    (setq which-key-idle-delay 0.3))

#+end_src

** Editing Configuration
*** Tab Widths and Spaces For Indentation

Default to an indentation size of 4 spaces 

#+begin_src emacs-lisp

  (setq-default tab-width 4)
  (setq-default evil-shift-width tab-width)
 
#+end_src

And use spaces for indentation instead of the default tabs.

#+begin_src emacs-lisp

  (setq-default indent-tabs-mode nil)

#+end_src

*** Commenting Lines

[[https://github.com/emacsmirror/evil-nerd-commenter][Evil-nerd-commenter]] makes it much more efficient to comment lines out. See their Github for examples of practical usage.

#+begin_src emacs-lisp

  (use-package evil-nerd-commenter
    :straight t
    :bind ("M-/" . evilnc-comment-or-uncomment-lines))

#+end_src

*** Automatically clean whitespace

#+begin_src emacs-lisp :tangle no

  (use-package ws-butler
    :straight t
    :hook ((text-mode . ws-butler-mode)
           (prog-mode . ws-butler-mode)))

#+end_src

** File-Management
*** Dired

[[https://www.gnu.org/software/emacs/manual/html_node/emacs/Dired.html][Dired]] is a built-in file manager for Emacs that does some pretty amazing things! I copied the next part from the emacs-from-scratch config, because it is so helpful. Here are some key bindings you should try out:

**** Key Bindings

***** Navigation

*Emacs* / *Evil*
- =n= / =j= - next line
- =p= / =k= - previous line
- =j= / =J= - jump to file in buffer
- =RET= - select file or directory
- =^= - go to parent directory
- =S-RET= / =g O= - Open file in "other" window
- =M-RET= - Show file in other window without focusing (previewing files)
- =g o= (=dired-view-file=) - Open file but in a "preview" mode, close with =q=
- =g= / =g r= Refresh the buffer with =revert-buffer= after changing configuration (and after filesystem changes!)

***** Marking files

- =m= - Marks a file
- =u= - Unmarks a file
- =U= - Unmarks all files in buffer
- =* t= / =t= - Inverts marked files in buffer
- =% m= - Mark files in buffer using regular expression
- =*= - Lots of other auto-marking functions
- =k= / =K= - "Kill" marked items (refresh buffer with =g= / =g r= to get them back)
- Many operations can be done on a single file if there are no active marks!

***** Copying and Renaming files

- =C= - Copy marked files (or if no files are marked, the current file)
- Copying single and multiple files
- =U= - Unmark all files in buffer
- =R= - Rename marked files, renaming multiple is a move!
- =% R= - Rename based on regular expression: =^test= , =old-\&=

*Power command*: =C-x C-q= (=dired-toggle-read-only=) - Makes all file names in the buffer editable directly to rename them!  Press =Z Z= to confirm renaming or =Z Q= to abort.

***** Deleting files

- =D= - Delete marked file
- =d= - Mark file for deletion
- =x= - Execute deletion for marks
- =delete-by-moving-to-trash= - Move to trash instead of deleting permanently
  
***** Creating and extracting archives

- =Z= - Compress or uncompress a file or folder to (=.tar.gz=)
- =c= - Compress selection to a specific file
- =dired-compress-files-alist= - Bind compression commands to file extension

***** Other common operations

- =T= - Touch (change timestamp)
- =M= - Change file mode
- =O= - Change file owner
- =G= - Change file group
- =S= - Create a symbolic link to this file
- =L= - Load an Emacs Lisp file into Emacs

**** Configuration

#+begin_src emacs-lisp

  (use-package dired
    :straight nil
    :commands (dired dired-jump)
    :bind (("C-x C-j" . dired-jump))
    :custom ((dired-listing-switches "-agho --group-directories-first"))
    :config
    (evil-collection-define-key 'normal 'dired-mode-map
      "h" 'dired-single-up-directory
      "l" 'dired-single-buffer))

  (use-package dired-single
    :straight t
    :commands (dired dired-jump))

  ;; (use-package all-the-icons-dired
  ;;   :straight t
  ;;   :hook (dired-mode . all-the-icons-dired-mode))

  (use-package dired-open
    :straight t
    :commands (dired dired-jump)
    :config
    ;; Doesn't work as expected!
    ;;(add-to-list 'dired-open-functions #'dired-open-xdg t)
    (setq dired-open-extensions '(("png" . "feh")
                                  ("pdf" . "zathura")
                                  ("mkv" . "mpv"))))

  (use-package dired-hide-dotfiles
    :straight t
    :hook (dired-mode . dired-hide-dotfiles-mode)
    :config
    (evil-collection-define-key 'normal 'dired-mode-map
      "H" 'dired-hide-dotfiles-mode))
#+end_src

** Development
*** Projectile

#+begin_src emacs-lisp

  (use-package projectile
    :straight t
    :config (projectile-mode)
    :demand t
    :init
    (setq projectile-project-search-path (list "~/Development/"
                                               )))

  (mb/leader-key-def
    "p"   '(:ignore t                  :which-key "Projectile")
    "pf"  'projectile-find-file
    "pp"  'projectile-switch-project
    ;; "pF"  'consult-ripgrep
    "pd"  'projectile-dired)

#+end_src

*** Magit

https://magit.vc/manual/magit/

#+begin_src emacs-lisp

  (use-package magit
    :straight t 
    :bind
    ("C-x g" . magit)
    :commands (magit-status magit-get-current-branch)
    :custom
    (magit-display-buffer-function #'magit-display-buffer-same-window-except-diff-v1))
#+end_src

*** Languages
**** Markdown

#+begin_src emacs-lisp

  (use-package markdown-mode
    :straight t
    :mode "\\.md\\'"
    :config
    (setq markdown-command "marked")
    (defun mb/set-markdown-header-font-sizes ()
      (dolist (face '((markdown-header-face-1 . 1.2)
                      (markdown-header-face-2 . 1.1)
                      (markdown-header-face-3 . 1.0)
                      (markdown-header-face-4 . 1.0)
                      (markdown-header-face-5 . 1.0)))
        (set-face-attribute (car face) nil :weight 'normal :height (cdr face))))

    (defun mb/markdown-mode-hook ()
      (mb/set-markdown-header-font-sizes))

    (add-hook 'markdown-mode-hook 'mb/markdown-mode-hook))

#+end_src

**** Nix

#+begin_src emacs-lisp :tangle no

  (use-package nix-mode
    :straight t
    :mode "\\.nix\\'")

#+end_src

**** Python

#+begin_src emacs-lisp
        (straight-use-package 'lsp-mode)
      (use-package lsp-ui
        :commands lsp-ui-mode
        :straight t)

      (add-hook 'python-mode-hook 'lsp-deferred)


    (use-package lsp-pyright
     :straight t
    :ensure t
    :custom (lsp-pyright-langserver-command "pyright") ;; or basedpyright
    :hook (python-mode . (lambda ()
                            (require 'lsp-pyright)
                            (lsp))))  ; or lsp-deferred
    ;; (use-package pyvenv
    ;;   :straight t
    ;;   :config
    ;;   (pyvenv mode))
  (use-package format-all
    :straight t
    :commands format-all-mode
    :hook (prog-mode . format-all-mode)
    :config
    (setq-default format-all-formatters
                  '(("Python"     (black)))))
      
          (use-package elpy
            :straight t
            :config
            (elpy-enable))

          

#+end_src

** Org Mode

=Org mode= is what makes Emacs most special; it's what drove me to Emacs and convinced me to stay. I discovered Emacs while reading [[https://gettingthingsdone.com/][Getting Things Done]] and both seemed to work really great together. Org comes with many different modules and functions, but works even better with some basic configuration.

*** Org UI

First, let's define a function for better fonts in =org files=. Make sure =Cantarell= fonts are installed.

#+begin_src emacs-lisp

  (defun mb/org-font-setup ()
    ;; Replace list hyphen with dot
    (font-lock-add-keywords 'org-mode
                            '(("^ *\\([-]\\) "
                               (0 (prog1 () (compose-region (match-beginning 1) (match-end 1) "•"))))))

    ;; Set faces for heading levels
    (dolist (face '((org-level-1 . 1.2)
                    (org-level-2 . 1.1)
                    (org-level-3 . 1.05)
                    (org-level-4 . 1.0)
                    (org-level-5 . 1.1)
                    (org-level-6 . 1.1)
                    (org-level-7 . 1.1)
                    (org-level-8 . 1.1)))
      (set-face-attribute (car face) nil :font "Cantarell" :weight 'regular :height 150))
      ;; (set-face-attribute (car face) nil :font "Inconsolata Nerd Font Mono" :weight 'regular :height (cdr face)))

    ;; Ensure that anything that should be fixed-pitch in Org files appears that way
    (set-face-attribute 'org-block nil    :foreground nil :inherit 'fixed-pitch)
    (set-face-attribute 'org-table nil    :inherit 'fixed-pitch)
    (set-face-attribute 'org-formula nil  :inherit 'fixed-pitch)
    (set-face-attribute 'org-code nil     :inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-table nil    :inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-verbatim nil :inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-special-keyword nil :inherit '(font-lock-comment-face fixed-pitch))
    (set-face-attribute 'org-meta-line nil :inherit '(font-lock-comment-face fixed-pitch))
    (set-face-attribute 'org-checkbox nil  :inherit 'fixed-pitch)
    (set-face-attribute 'line-number nil :inherit 'fixed-pitch)
    (set-face-attribute 'line-number-current-line nil :inherit 'fixed-pitch))

#+end_src

Next, set up a function for org-mode hook. This makes sure:
- the buffer is displayed in the indented view
- we get /proportional fonts/ in the buffer, makes it nicer to look at
- /word-wrap/ is turned on and editing commands act on visual lines, not logical lines
- enable visual-fill

#+begin_src emacs-lisp

  (defun mb/org-mode-visual-fill ()
    (setq visual-fill-column-width 120
          visual-fill-column-center-text t)
    (visual-fill-column-mode 1))

  (use-package visual-fill-column
    :straight t
    :defer t)

  (defun mb/org-mode-setup ()
    (org-indent-mode)
    (variable-pitch-mode 1)
    (visual-line-mode 1)
    (mb/org-mode-visual-fill))

#+end_src

*** Configuration

Here, we start the actual configuration. The first part of the config sets-up various things, such as:

- A nicer symbol to show there is hidden content
- Hide emphasis markers so we see *bold* instead of **bold**
- Make sure at startup content is =folded=
- Extra =evil= key definitions

#+begin_src emacs-lisp

  (straight-use-package '(org :type built-in))

  (use-package org
    :defer t
    :hook (org-mode . mb/org-mode-setup)
    :config
    (setq org-ellipsis " ▾"
          org-hide-emphasis-markers t
          org-src-fontify-natively t
          org-fontify-quote-and-verse-blocks t
          org-src-tab-acts-natively t
          org-edit-src-content-indentation 2
          org-hide-block-startup nil
          org-src-preserve-indentation nil
          org-startup-folded 'content
          org-cycle-separator-lines 2)

    (evil-define-key '(normal insert visual) org-mode-map (kbd "C-j") 'org-next-visible-heading)
    (evil-define-key '(normal insert visual) org-mode-map (kbd "C-k") 'org-previous-visible-heading)

    (evil-define-key '(normal insert visual) org-mode-map (kbd "M-j") 'org-metadown)
    (evil-define-key '(normal insert visual) org-mode-map (kbd "M-k") 'org-metaup)

#+end_src

*NOTE* This is not the /end/ of our =use-package= block!

*** Workflow

My workflow is documented in a seperate file. It just needs to be called from here.

#+begin_src emacs-lisp :tangle no

  (require 'mb-workflow)

#+end_src

*** Modules

Enable some modules which are quite handy, such as =habits=

#+begin_src emacs-lisp

  (setq org-modules
        '(org-habit))


#+end_src

*** Block Templates

These templates enable you to type things like =<el= and then hit =Tab= to expand
the template. More documentation can be found at the Org Mode [[https://orgmode.org/manual/Easy-templates.html][Easy Templates]]
documentation page.

#+begin_src emacs-lisp

  ;; This is needed as of Org 9.2
  (require 'org-tempo)

  (add-to-list 'org-structure-template-alist '("sh" . "src sh"))
  (add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
  (add-to-list 'org-structure-template-alist '("ni" . "src nix"))
  (add-to-list 'org-structure-template-alist '("py" . "src python"))
  (add-to-list 'org-structure-template-alist '("r"  . "src rust"))

#+end_src

*** Org Bullets using Superstar

The default heading stars are not very visually attractive. I replace this with [[https://github.com/integral-dw/org-superstar-mode][org-superstar-mode]] and define a custom bullet list.

#+begin_src emacs-lisp

  (use-package org-superstar
    :straight t
    :after org
    :hook (org-mode . org-superstar-mode)
    :custom
    (org-superstar-remove-leading-stars t)
    (org-superstar-headline-bullets-list '("◉" "○" "●" "○" "●" "○" "●")))

#+end_src

*** End of =use-package org=

And finally, load our font setup (see function at the beginning of this org block) and end our =use-package org= block with a parenthesis.

#+begin_src emacs-lisp

  (mb/org-font-setup))

#+end_src

*** Journal

#+begin_src emacs-lisp
  (use-package org-journal
    :ensure t
    :straight t
    :init
    ;; Change default prefix key; needs to be set before loading org-journal
    (setq org-journal-prefix-key "C-c j ")
    :config
    (setq org-journal-dir "~/Documenten/org/journal/"
          org-journal-date-format "%Y-%m-%d"
          org-journal-file-format "%Y-%m-%d.org"))
#+end_src

** Completion Framework

There are many packages which provide completion frameworks, such as =ivy= and =helm=. Recently, I started using =vertico=, =consult=, =marginalia= and others. These are somewhat /smaller/ since they are built upon basic functionality that Emacs already provides. It is important to have =ripgrep= installed as this is notably faster than standar =grep=.

*** Vertico

[[https://github.com/minad/vertico][Vertico]] is a relatively new package created by Minad which displays a minimalistic vertical compeletion UI. It is builts further upon the built-in functionality that Emacs provides. This makes it different from [[https://github.com/abo-abo/swiper][Ivy]] which is a complete generic completion system. Therefore, we have to custimize it a bit further. Below is the basic config as taken from github.

#+begin_src emacs-lisp

  ;; Enable vertico
  (use-package vertico
    :straight '(vertico :host github
                        :repo "minad/vertico"
                        :branch "main")
    :init
    (vertico-mode)

    ;; Optionally enable cycling for `vertico-next' and `vertico-previous'.
    ;; (setq vertico-cycle t)
    )

  ;; Use the `orderless' completion style.
  ;; Enable `partial-completion' for files to allow path expansion.
  ;; You may prefer to use `initials' instead of `partial-completion'.
  (use-package orderless
    :straight t
    :init
    (setq completion-styles '(orderless)
          completion-category-defaults nil
          completion-category-overrides '((file (styles . (partial-completion))))))

  ;; Persist history over Emacs restarts. Vertico sorts by history position.
  (use-package savehist
    :straight t
    :init
    (savehist-mode))

#+end_src

*** Marginalia

[[https://github.com/minad/marginalia][Marginalia]] provides rich annotations. It is made by the same person who developed =Vertico= and many other useful packages. Marginalia for instance shows extra useful information in the minibuffer.

#+begin_src emacs-lisp

  ;; Enable richer annotations using the Marginalia package
  (use-package marginalia
    :after vertico
    :straight t
    ;; Either bind `marginalia-cycle` globally or only in the minibuffer
    :bind (:map minibuffer-local-map
                ("M-A" . marginalia-cycle))

    ;; The :init configuration is always executed (Not lazy!)
    :init

    ;; Must be in the :init section of use-package such that the mode gets
    ;; enabled right away. Note that this forces loading the package.
    (marginalia-mode))

#+end_src

*** Consult

#+begin_src emacs-lisp
  ;; Consult
  (use-package consult
    :straight t ;; Install with straight
    ;; Replace bindings. Lazily loaded due by `use-package'.
    :bind (;; C-c bindings (mode-specific-map)
           ;; C-x bindings (ctl-x-map)
           ("C-x M-:" . consult-complex-command)     ;; orig. repeat-complex-command
           ("C-x b" . consult-buffer)                ;; orig. switch-to-buffer
           ("C-x 4 b" . consult-buffer-other-window) ;; orig. switch-to-buffer-other-window
           ("C-x 5 b" . consult-buffer-other-frame)  ;; orig. switch-to-buffer-other-frame
           ;; Isearch integration
           ("C-s" . consult-line)
           :map isearch-mode-map
           ("M-e" . consult-isearch)                 ;; orig. isearch-edit-string
           ("M-s e" . consult-isearch)               ;; orig. isearch-edit-string
           ("M-s l" . consult-line))                 ;; required by consult-line to detect isearch

    ;; Enable automatic preview at point in the *Completions* buffer.
    ;; This is relevant when you use the default completion UI,
    ;; and not necessary for Selectrum, Vertico etc.
    :hook (completion-list-mode . consult-preview-at-point-mode)

    ;; The :init configuration is always executed (Not lazy)
    :init

    ;; Optionally configure the register formatting. This improves the register
    ;; preview for `consult-register', `consult-register-load',
    ;; `consult-register-store' and the Emacs built-ins.
    (setq register-preview-delay 0
          register-preview-function #'consult-register-format)

    ;; Optionally tweak the register preview window.
    ;; This adds thin lines, sorting and hides the mode line of the window.
    (advice-add #'register-preview :override #'consult-register-window)

    ;; Use Consult to select xref locations with preview
    (setq xref-show-xrefs-function #'consult-xref
          xref-show-definitions-function #'consult-xref)

    ;; Configure other variables and modes in the :config section,
    ;; after lazily loading the package.
    :config

    ;; Optionally configure preview. The default value
    ;; is 'any, such that any key triggers the preview.
    ;; (setq consult-preview-key 'any)
    ;; (setq consult-preview-key (kbd "M-."))
    ;; (setq consult-preview-key (list (kbd "<S-down>") (kbd "<S-up>")))
    ;; For some commands and buffer sources it is useful to configure the
    ;; :preview-key on a per-command basis using the `consult-customize' macro.
    (consult-customize
     consult-ripgrep consult-git-grep consult-grep
     consult-bookmark consult-recent-file consult-xref
     consult--source-bookmark consult--source-recent-file
     consult--source-project-recent-file
     :preview-key (kbd "M-."))

    ;; Optionally configure the narrowing key.
    ;; Both < and C-+ work reasonably well.
    (setq consult-narrow-key "<") ;; (kbd "C-+")

    ;; Optionally make narrowing help available in the minibuffer.
    ;; You may want to use `embark-prefix-help-command' or which-key instead.
    ;; (define-key consult-narrow-map (vconcat consult-narrow-key "?") #'consult-narrow-help)

    ;; Optionally configure a function which returns the project root directory.
    ;; There are multiple reasonable alternatives to chose from.
     ;;;; 1. project.el (project-roots)
    (setq consult-project-root-function
          (lambda ()
            (when-let (project (project-current))
              (car (project-roots project)))))
     ;;;; 2. projectile.el (projectile-project-root)
    ;; (autoload 'projectile-project-root "projectile")
    ;; (setq consult-project-root-function #'projectile-project-root)
     ;;;; 3. vc.el (vc-root-dir)
    ;; (setq consult-project-root-function #'vc-root-dir)
     ;;;; 4. locate-dominating-file
    ;; (setq consult-project-root-function (lambda () (locate-dominating-file "." ".git")))
    (setq recentf-mode t)
    )

#+end_src

*** Corfu

#+begin_src emacs-lisp

      (straight-use-package
       '(corfu-terminal
         :type git
         :repo "https://codeberg.org/akib/emacs-corfu-terminal.git"))

    (unless (display-graphic-p)
      (corfu-terminal-mode +1))

        (use-package corfu
          :straight t
          ;; Optional customizations
          :custom
          (corfu-cycle t)                ;; Enable cycling for `corfu-next/previous'
          (corfu-auto t)
          (corfu-auto-prefix 2)
          (corfu-auto-delay 0.0)
          (corfu-quit-at-boundary 'separator)   ;; Never quit at completion boundary
          (corfu-echo-documentation 0.25)
          (corfu-preview-current 'insert)    ;; Disable current candidate preview
          (corfu-preselect-first nil)      ;; Preselect the prompt
          :bind (:map corfu-map
                      ("M-SPC"   . corfu-insert-separator)
                      ("RET"     . nil)
                      ("TAB"     . corfu-next)
                      ([tab]     . corfu-next)
                      ("S-TAB"   . corfu-previous)
                      ([backtab] . corfu-previous)
                      ("S-<return>" . corfu-insert))
          ;; Enable Corfu only for certain modes. See also `global-corfu-modes'.
          ;; :hook ((prog-mode . corfu-mode)
          ;;        (shell-mode . corfu-mode)
          ;;        (eshell-mode . corfu-mode))
          :init
          ;; Recommended: Enable Corfu globally.  Recommended since many modes provide
          ;; Capfs and Dabbrev can be used globally (M-/).  See also the customization
          ;; variable `global-corfu-modes' to exclude certain modes.
          (global-corfu-mode)
          (corfu-history-mode)
          ;; (corfu-popupinfo-mode)
          :config
          (add-hook 'eshell-mode-hook
                    (lambda () (setq-local corfu-quit-at-boundary t
                                           corfu-quit-no-match t
                                           corfu-auto nil)
                      (corfu-mode))))

    (use-package cape
    :straight t
    ;; Bind prefix keymap providing all Cape commands under a mnemonic key.
    ;; Press C-c p ? to for help.
    :bind ("C-c p" . cape-prefix-map) ;; Alternative key: M-<tab>, M-p, M-+
    ;; Alternatively bind Cape commands individually.
    ;; :bind (("C-c p d" . cape-dabbrev)
    ;;        ("C-c p h" . cape-history)
    ;;        ("C-c p f" . cape-file)
    ;;        ...)
    :init
    ;; Add to the global default value of `completion-at-point-functions' which is
    ;; used by `completion-at-point'.  The order of the functions matters, the
    ;; first function returning a result wins.  Note that the list of buffer-local
    ;; completion functions takes precedence over the global list.
    (add-hook 'completion-at-point-functions #'cape-dabbrev)
    (add-hook 'completion-at-point-functions #'cape-file)
    (add-hook 'completion-at-point-functions #'cape-elisp-block)
    ;; (add-hook 'completion-at-point-functions #'cape-history)
    ;; ...
  )
#+end_src

*** Orderless

#+begin_src emacs-lisp

  (use-package orderless
    :straight t
    :custom
    ;; (orderless-style-dispatchers '(orderless-affix-dispatch))
    ;; (orderless-component-separator #'orderless-escapable-split-on-space)
    (completion-styles '(orderless basic))
    (completion-category-defaults nil)
    (completion-category-overrides '((file (styles partial-completion)))))

#+end_src

** Useful Packages
*** Helpful

[[https://github.com/Wilfred/helpful][Helpful]] is a very helpful package that aims to be an alternative for the built-in and provides much more contextual information. For instance, in addition to the basic documentation, you will also see the source code of the function and where it gets used in other places in the Emacs configuration. It is very useful for figuring out how things work in Emacs.

#+begin_src emacs-lisp

  (use-package helpful
    :straight t
    :config
    ;; Note that the built-in `describe-function' includes both functions
    ;; and macros. `helpful-function' is functions only, so we provide
    ;; `helpful-callable' as a drop-in replacement.
    (global-set-key (kbd "C-h f") #'helpful-callable)

    (global-set-key (kbd "C-h v") #'helpful-variable)
    (global-set-key (kbd "C-h k") #'helpful-key)

    ;; Look up *F*unctions (excludes macros).
    ;;
    ;; By default, C-h F is bound to `Info-goto-emacs-command-node'. Helpful
    ;; already links to the manual, if a function is referenced there.
    (global-set-key (kbd "C-h F") #'helpful-function)

    ;; Look up *C*ommands.
    ;;
    ;; By default, C-h C is bound to describe `describe-coding-system'. I
    ;; don't find this very useful, but it's frequently useful to only
    ;; look at interactive functions.
    (global-set-key (kbd "C-h C") #'helpful-command))

#+end_src

** Runtime Performance

Dial the GC threshold back down so that garbage collection happens more frequently but in less time.

#+begin_src emacs-lisp

  ;; Make gc pauses faster by decreasing the threshold.
  (setq gc-cons-threshold (* 2 1000 1000))

#+end_src

