# preload = ~/.config/backgrounds/tetris.png
preload = ~/.config/backgrounds/black_minimal.jpg
# wallpaper = , ~/.config/backgrounds/tetris.png
wallpaper = , ~/.config/backgrounds/black_minimal.jpg
# wallpaper = , ~/.config/backgrounds/shaded.png
