#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = hyprctl setcursor catppuccin-mocha-dark-cursors 28
# exec-once = $terminal
exec-once = nm-applet &
# exec-once = blueman-applet &
exec-once = waybar & hyprpaper & hypridle & mako

# Clipboard management
# exec-once = wl-paste --type text --watch cliphist store # Stores only text data
# exec-once = wl-paste --type image --watch cliphist store # Stores only image data

# Autostart Emacs and Glow
# exec-once = [workspace 1 silent] kitty -e emacsclient -nw
# exec-once = [workspace 2 silent] kitty -e ~/.config/scripts/launch-glow.sh

exec-once = wl-clip-persist --clipboard regular & clipse -listen
