################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=,highres,auto,1.6
# monitor=,highres,auto,1.67
# monitor=DP-1,3840x2160,0x0,1.333333

### DISABLE LAPTOP MONITOR WHEN LID CLOSES
# trigger when the switch is turning on
bindl = , switch:on:Lid Switch, exec, hyprctl keyword monitor "eDP-1, disable"
# trigger when the switch is turning off
bindl = , switch:off:Lid Switch, exec, hyprctl keyword monitor "eDP-1, highres, auto, 1.67"

# Bind workspaces to monitor
# 1-5 to eDP-1 (laptop screen)
# 0, 6-9 to DP-1 (Dell external monitor)
workspace = 1, monitor:eDP-1
workspace = 2, monitor:eDP-1
workspace = 3, monitor:eDP-1
workspace = 4, monitor:eDP-1
workspace = 5, monitor:eDP-1

workspace = 6, monitor:DP-1
workspace = 7, monitor:DP-1
workspace = 8, monitor:DP-1
workspace = 9, monitor:DP-1
workspace = 0, monitor:DP-1

# unscale XWayland
xwayland {
  force_zero_scaling = true
}

# Problem with floating Kitty
windowrule = tile, xwayland:1

# Float sound and bluetooth settings
windowrule = float, class:^(org.pulseaudio.pavucontrol|blueman-manager|pinentry-gtk)$

# Proper background blur for wofi
layerrule = blur,wofi

# Float in the middle for clipse clipboard manager
windowrule = float, class:(clipse)
windowrule = size 622 652, class:(clipse)
windowrule = stayfocused, class:(clipse)

# Float and cneter file pickers
windowrule = float, class:xdg-desktop-portal-gtk, title:^(Open.*Files?|Save.*Files?)
windowrule = center, class:xdg-desktop-portal-gtk, title:^(Open.*Files?|Save.*Files?)
