################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=,highres,auto,1.67
# monitor=DP-1,3840x2160,0x0,1.333333

### DISABLE LAPTOP MONITOR WHEN LID CLOSES
# trigger when the switch is turning on
bindl = , switch:on:Lid Switch, exec, hyprctl keyword monitor "eDP-1, disable"
# trigger when the switch is turning off
bindl = , switch:off:Lid Switch, exec, hyprctl keyword monitor "eDP-1, highres, auto, 1.67"


# unscale XWayland
xwayland {
  force_zero_scaling = true
}

