preload = ~/.config/backgrounds/minimal.jpg
# preload = ~/.config/backgrounds/black_mountain.jpg
wallpaper = , ~/.config/backgrounds/minimal.jpg
# wallpaper = , ~/.config/backgrounds/black_mountain.jpg
# wallpaper = , ~/.config/backgrounds/shaded.png
